# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e788ece8bc1ae5eeff4a8d2d516da3c756e5892f10fe37a4a565239dcde8889677748c9ec4044d2fd5354cf6f7ff4372b95cf6dff658254e308c658a541a259b

test:
  secret_key_base: 552d8ea6852844ab70fa0214d03c4d4760fe9897ed8558f500caa9bdfd847afafeaed80eb141b7ea88ea112e64b237654b7273526370ed7bdade579635c99143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
